# Generated by Django 5.0.3 on 2024-03-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number_of_draws',
            field=models.IntegerField(default=0),
        ),
    ]
