# Generated by Django 5.0.3 on 2024-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_number_of_draws'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.TextField(default=''),
        ),
    ]
