# Generated by Django 5.0.3 on 2024-03-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_player_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='division',
            new_name='league',
        ),
    ]
