# Generated by Django 5.0.3 on 2024-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_division_team_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number_of_teams', models.PositiveIntegerField()),
                ('year_founded', models.PositiveIntegerField()),
            ],
        ),
    ]
